language: csharp
sudo: required
dist: xenial
mono: latest
dotnet: 2.2
before_install:
  - sudo apt-get install -y texlive texlive-lang-cyrillic texlive-latex-extra python-pygments ghostscript
  - export TRAVIS_REPO_NAME=$(echo "${TRAVIS_REPO_SLUG#*/}" | sed 's/.*/\u&/')
  - export SOURCE_BRANCH="master"
script:
  - dotnet build -c Release
  - dotnet test -c Release -f netcoreapp2.1
after_success:
  - bash ./generate-pdf.sh
  - bash ./publish-docs.sh
  - bash ./push-nuget.sh
